# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
