# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hbeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.IntegerField()),
                ('Created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hpluse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hpres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hrelax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Htem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
