# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0002_auto_20170317_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hbeat',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hpluse',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hpres',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hrelax',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='htem',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
