# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0003_auto_20170317_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hbeat',
        ),
        migrations.RemoveField(
            model_name='hpluse',
            name='Created_at',
        ),
        migrations.RemoveField(
            model_name='hpres',
            name='Created_at',
        ),
        migrations.RemoveField(
            model_name='hrelax',
            name='Created_at',
        ),
        migrations.RemoveField(
            model_name='htem',
            name='Created_at',
        ),
        migrations.AlterField(
            model_name='hpluse',
            name='values',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hpres',
            name='values',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hrelax',
            name='values',
            field=models.IntegerField(),
        ),
    ]
