# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 09:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0008_auto_20170320_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpluse',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 9, 31, 37, 159000, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='hpres',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 9, 31, 37, 158000, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='hrelax',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 9, 31, 37, 158000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='htem',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 9, 31, 37, 157000, tzinfo=utc)),
        ),
    ]
