# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 07:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0009_auto_20170320_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpluse',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 26, 7, 10, 39, 473000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hpres',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 26, 7, 10, 39, 472000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hrelax',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 26, 7, 10, 39, 472000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='htem',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 26, 7, 10, 39, 471000, tzinfo=utc)),
        ),
    ]
