# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 02:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0010_auto_20170326_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpluse',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 28, 2, 51, 22, 339000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hpres',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 28, 2, 51, 22, 338000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hrelax',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 28, 2, 51, 22, 338000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='htem',
            name='ctime',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 28, 2, 51, 22, 337000, tzinfo=utc)),
        ),
    ]
